version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  admin-server:
    container_name: admin-server
    build:
      context: ./admin-server
    ports:
      - "8000:8000"
    environment:
      server.port: 8000

  transformation:
    container_name: transformation
    build:
      context: ./transformation
    depends_on:
      - zookeeper
      - kafka
      - admin-server
    ports:
      - "8025:8025"
    environment:
      server.port: 8025
      spring.kafka.bootstrap-servers: kafka:9092
      spring.datasource.hikari.maximum-pool-size: 10
      spring.boot.admin.client.url: http://admin-server:8000/
