version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  eureka-server:
    container_name: eureka-server
    image: eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      PORT: 8761

  admin-server:
    container_name: admin-server
    image: admin-server:latest
    depends_on:
      - eureka-server
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      EUREKA-SERVER: http://eureka-server:8761/eureka

  transformation:
    container_name: transformation
    image: transformation:latest
    depends_on:
      - zookeeper
      - kafka
      - eureka-server
      - admin-server
    ports:
      - "8025:8025"
    environment:
      PORT: 8025
      KAFKA-SERVER: kafka:9092
      EUREKA-SERVER: http://eureka-server:8761/eureka
      spring.datasource.hikari.maximum-pool-size: 10
